;;;; $Id: cyrillic-dvorak-programming.el,v 0.1 2013/11/07 07:06:31 ksander314 Exp $
;;;; $Author: ksander314 $
;;;; Distributed under the GPL

;;;; If you're using `dvorak-programming' keyboard layout and also need writing russian in
;;;; the `jcuken' layout, you may find this package helpful!
;;;; Based on 'cyrillic-dvorak' by kirill.

(require 'quail)

(quail-define-package
 "cyrillic-dvorak-programming" "Cyrillic" "RUdvp" nil
 "ЙЦУКЕН keyboard layout widely used in Russia (ISO 8859-5 encoding)
  in assuming that your default keyboard layout is dvorak programming"
 nil t t t t nil nil nil nil nil t)

;;  1! 2" 3' 4; 5 6: 7? 8 9( 0) -_ =+ Ё
;;   Й  Ц  У  К  Е  Н  Г  Ш  Щ  З  Х  ъ
;;    Ф  Ы  В  А  П  Р  О  Л  Д Ж  Э
;;     Я  Ч  С  М  И  Т  Ь  Б  Ю  .,

(quail-define-rules
 ("&" ?1)
 ("[" ?2)
 ("{" ?3)
 ("}" ?4)
 ("(" ?5)
 ("=" ?6)
 ("*" ?7)
 (")" ?8)
 ("+" ?9)
 ("]" ?0)
 ("!" ?-)
 ("#" ?=)
 ("$" ?ё)
 (";" ?й)
 ("," ?ц)
 ("." ?у)
 ("p" ?к)
 ("y" ?е)
 ("f" ?н)
 ("g" ?г)
 ("c" ?ш)
 ("r" ?щ)
 ("l" ?з)
 ("/" ?х)
 ("@" ?ъ)
 ("a" ?ф)
 ("o" ?ы)
 ("e" ?в)
 ("u" ?а)
 ("i" ?п)
 ("d" ?р)
 ("h" ?о)
 ("t" ?л)
 ("n" ?д)
 ("s" ?ж)
 ("-" ?э)
 ("\\" ?\\)
 ("'" ?я)
 ("q" ?ч)
 ("j" ?с)
 ("k" ?м)
 ("x" ?и)
 ("b" ?т)
 ("m" ?ь)
 ("w" ?б)
 ("v" ?ю)
 ("z" ?.)
 
 ("%" ?!)
 ("7" ?\")
 ("5" ?')
 ("3" ?\;)
 ("1" ?%)
 ("9" ?:)
 ("0" ??)
 ("2" ?*)
 ("4" ?()
 ("6" ?))
 ("8" ?_)
 ("`" ?+)
 ("~" ?Ё)
 (":" ?Й)
 ("<" ?Ц)
 (">" ?У)
 ("P" ?К)
 ("Y" ?Е)
 ("F" ?Н)
 ("G" ?Г)
 ("C" ?Ш)
 ("R" ?Щ)
 ("L" ?З)
 ("?" ?Х)
 ("^" ?Ъ)
 ("A" ?Ф)
 ("O" ?Ы)
 ("E" ?В)
 ("U" ?А)
 ("I" ?П)
 ("D" ?Р)
 ("H" ?О)
 ("T" ?Л)
 ("N" ?Д)
 ("S" ?Ж)
 ("_" ?Э)
 ("|" ?/)
 ("\"" ?Я)
 ("Q" ?Ч)
 ("J" ?С)
 ("K" ?М)
 ("X" ?И)
 ("B" ?Т)
 ("M" ?Ь)
 ("W" ?Б)
 ("V" ?Ю)
 ("Z" ?,))
