(setq inhibit-startup-screen t)
(setq initial-scratch-message "")
(setq visible-bell t)
(scroll-bar-mode 0)
(tool-bar-mode 0)
(menu-bar-mode 0)

(add-to-list 'load-path user-emacs-directory)
(require 'init-package)
(require 'init-utils)
(require 'init-font)
(require 'init-flymake)
(require 'init-c++)
(require 'init-haskell)
(require 'init-auto-complete)
(require 'init-locale)
(require 'init-theme)
(require 'init-mercurial)
(require 'init-hg-commit-message)
(require-package 'ox-reveal)

(desktop-save-mode t)
(require 'server)
(unless (server-running-p)
  (server-start))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
(setq user-mail-address "olexander314@gmail.com")
(setq user-login-name "Alexander Stepanenko")

(require-package 'git-gutter)
(global-git-gutter-mode +1)

(require-package 'google-translate)
(require 'google-translate)
(setq google-translate-default-target-language "ru")
(setq google-translate-default-source-language "en")
(global-set-key "\C-ct" 'google-translate-at-point)
(global-set-key "\C-cT" 'google-translate-query-translate)

(defalias 'list-buffers 'ibuffer)
