(require-package 'go-mode)
(require-package 'go-guru)
(require-package 'gotest)
(require-package 'go-rename)
(require-package 'dap-mode)
(defun my-go-mode-hook ()
  (add-hook 'go-mode-hook (lambda () (auto-complete-mode -1)))
  (add-hook 'go-mode-hook 'hl-line-mode)
  (add-hook 'dap-stopped-hook
          (lambda (arg) (call-interactively #'dap-hydra)))
  (local-set-key (kbd "C-c c") 'compile)
  (setq gofmt-command "goimports")
  (add-hook 'before-save-hook 'gofmt-before-save)
  (local-set-key (kbd "C-c C-g") 'go-guru-definition)
  (local-set-key (kbd "C-c C-r") 'go-guru-referrers)
  (local-set-key (kbd "C-c C-i") 'go-guru-implements)
  (local-set-key (kbd "C-c C-f") 'pop-tag-mark)
  (local-set-key (kbd "C-c C-s") 'dap-debug)
  (local-set-key (kbd "C-c C-b") 'dap-breakpoint-toggle)
  (if (not (string-match "go" compile-command))
      (set (make-local-variable 'compile-command)
           "go build -v && go test -v && go vet"))
  )
(add-hook 'go-mode-hook 'my-go-mode-hook)
(add-hook 'go-mode-hook 'subword-mode)
(add-hook 'go-mode-hook 'which-function-mode)
(require 'whitespace)
(setq whitespace-line-column 80)
(add-hook 'go-mode-hook 'lsp-deferred)
(require 'dap-go)
(provide 'init-go)
