(require-package 'rust-mode)
(require-package 'projectile)
(require-package 'lsp-ui)
(require 'rust-mode)
(require-package 'lsp-mode)
(require 'lsp-mode)
(autoload 'rust-mode "rust-mode" nil t)
(defun my-rust-mode-hook ()
  (local-set-key (kbd "C-c C-p") 'projectile-commander)
  (setq lsp-rust-server 'rust-analyzer)
  (setq lsp-rust-analyzer-cargo-watch-command "clippy")
  (setq lsp-eldoc-render-all t)
  (setq lsp-idle-delay 0.7)
  (setq lsp-rust-analyzer-server-display-inlay-hints t)
  
  (setq lsp-ui-peek-always-show t)
  (setq lsp-ui-sideline-show-hover t)
  (setq lsp-ui-doc-enable nil)
  (add-hook 'rust-mode-hook 'lsp-ui-mode)
  )
(add-hook 'rust-mode-hook 'my-rust-mode-hook)
(add-hook 'rust-mode-hook
          (lambda () (setq indent-tabs-mode nil)))
(add-hook 'rust-mode-hook 'projectile-mode)
(setq rust-format-on-save t)
(define-key rust-mode-map (kbd "C-c c") 'rust-compile)
(define-key rust-mode-map (kbd "C-c r") 'rust-run)
(define-key rust-mode-map (kbd "C-c l") 'rust-run-clippy)
(define-key rust-mode-map (kbd "C-c C-r") 'lsp-find-references)
(define-key rust-mode-map (kbd "C-c C-i") 'lsp-find-implementation)

(require-package 'toml-mode)
(require 'toml-mode)
(add-hook 'rust-mode-hook
          (lambda () (lsp)))
(require-package 'cargo)
(require 'cargo)
(add-hook 'rust-mode-hook 'cargo-minor-mode)
(add-hook 'rust-mode-hook 'hl-line-mode)

(require-package 'flycheck-rust)
(require 'flycheck-rust)
(provide 'init-rust)
