(require-package 'flycheck-irony)
(add-hook 'c++-mode-hook 'flycheck-mode)
(global-set-key (kbd "C-c c") 'compile)
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 4)
(defun indentation-c++-mode-hook ()
  (c-set-offset 'substatement-open '0)
  (c-set-offset 'innamespace '0)
  (c-set-offset 'inline-open '0)
  (c-set-offset 'block-open '0)
  (c-set-offset 'brace-list-open '0))
(add-hook 'c++-mode-hook 'indentation-c++-mode-hook)
(add-hook 'c++-mode-hook 'subword-mode)
(add-hook 'c++-mode-hook 'which-function-mode)
(add-hook 'c++-mode-hook 'hl-line-mode)
(require 'whitespace)
(setq whitespace-line-column 80)
(setq whitespace-style '(face lines-tail tabs))
(add-hook 'c++-mode-hook 'whitespace-mode)
(require-package 'helm-gtags)
(add-hook 'c-mode-hook 'helm-gtags-mode)
(add-hook 'c++-mode-hook 'helm-gtags-mode)
(custom-set-variables
 '(helm-gtags-auto-update t))
(eval-after-load "helm-gtags"
  '(progn
     (define-key helm-gtags-mode-map (kbd "C-c g t") 'helm-gtags-find-tag)
     (define-key helm-gtags-mode-map (kbd "C-c g r") 'helm-gtags-find-rtag)
     (define-key helm-gtags-mode-map (kbd "C-c g s") 'helm-gtags-find-symbol)
     (define-key helm-gtags-mode-map (kbd "C-c C-g") 'helm-gtags-find-tag-from-here)
     (define-key helm-gtags-mode-map (kbd "C-c g f") 'helm-gtags-find-files)
     (define-key helm-gtags-mode-map (kbd "C-c C-f") 'helm-gtags-previous-history)))
(add-hook 'c-mode-hook 'hs-minor-mode)
(add-hook 'c++-mode-hook 'hs-minor-mode)
(add-hook 'c++-mode-hook (lambda () (setq show-trailing-whitespace t)))
(provide 'init-c++)
