(require-package 'rust-mode)
(require-package 'projectile)
(require 'rust-mode)
(require-package 'lsp-mode)
(require 'lsp-mode)
(autoload 'rust-mode "rust-mode" nil t)
(defun my-rust-mode-hook ()
  (local-set-key (kbd "C-c C-p") 'projectile-commander)
  )
(add-hook 'rust-mode-hook 'my-rust-mode-hook)
(add-hook 'rust-mode-hook
          (lambda () (setq indent-tabs-mode nil)))
(add-hook 'rust-mode-hook 'projectile-mode)
(setq rust-format-on-save t)
(define-key rust-mode-map (kbd "M-*") 'xref-pop-marker-stack)
(define-key rust-mode-map (kbd "C-c c") 'rust-run)
(define-key rust-mode-map (kbd "C-c l") 'rust-run-clippy)
(define-key rust-mode-map (kbd "C-c C-r") 'lsp-find-references)
(define-key rust-mode-map (kbd "C-c C-i") 'lsp-find-implementation)

(require-package 'toml-mode)
(require 'toml-mode)
(add-hook 'rust-mode-hook
          (lambda () (lsp)))
(require-package 'cargo)
(require 'cargo)
(add-hook 'rust-mode-hook 'cargo-minor-mode)

(require-package 'flycheck-rust)
(require 'flycheck-rust)
(require-package 'lsp-ui)
(require 'lsp-ui)
(require-package 'lsp-treemacs)
(require 'lsp-treemacs)
(provide 'init-rust)
